# site details
name: Life of a designer
description: 
url: http://llifeofadesigner.com

# social profiles. just remove unneeded profiles.
dribbble: razvanh
github: razvanh
instagram: razvanh
twitter: razvanh

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:title.html

exclude: [readme.md]
include: [.htaccess]