---
title: Load
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Life of a designer
description: 
url: http://llifeofadesigner.com
dribbble: razvanh
github: razvanh
instagram: razvanh
twitter: razvanh
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: "/:title.html"
exclude:
- readme.md
include:
- ".htaccess"
